"""empty message

Revision ID: 281cf4824712
Revises: 
Create Date: 2025-07-08 22:54:51.395235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281cf4824712'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='status'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', 'unknown', name='sentiment'), nullable=True),
    sa.Column('category', sa.Enum('техническая', 'оплата', 'другое', name='category'), nullable=True),
    sa.Column('geolocation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaits')
    # ### end Alembic commands ###
